name: Unit Tests

on:
  workflow_dispatch:

jobs:
  run-unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    container:
      image: utkusarioglu/ethereum-devcontainer:1.0.4
      options: --user=0:0
      env:
        COINMARKETCAP_API_KEY: ${{ secrets.COINMARKETCAP_API_KEY }}
        INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
        ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        ALCHEMY_ETHEREUM_KOVAN_API_KEY:
          ${{ secrets.ALCHEMY_ETHEREUM_KOVAN_API_KEY }}
        ALCHEMY_POLYGON_MUMBAI_API_KEY:
          ${{ secrets.ALCHEMY_POLYGON_MUMBAI_API_KEY }}
        GOERLI_DEPLOYER_PK: ${{ secrets.GOERLI_DEPLOYER_PK }}
        LOCAL_DEPLOYER_PK: ${{ secrets.LOCAL_DEPLOYER_PK }}
        LOCAL_USER_1_PK: ${{ secrets.LOCAL_USER_1_PK }}
        LOCAL_USER_2_PK: ${{ secrets.LOCAL_USER_2_PK }}
        LOCAL_USER_3_PK: ${{ secrets.LOCAL_USER_3_PK }}
        FORKING_ENABLED: ${{ secrets.FORKING_ENABLED }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install dependencies
        run: yarn --frozen-lockfile --no-progress --production false
      - name: Compile contracts
        run: yarn hardhat compile
      - name: Run unit tests
        run: yarn test

      - name: Telegram notifications
        if: always()
        uses: utkusarioglu/telegram-notifications@main
        with:
          telegram_id: ${{ secrets.TELEGRAM_ID }}
          telegram_token: ${{ secrets.TELEGRAM_TOKEN }}
          job_status: ${{ job.status }}
          github_context: ${{ toJson(github) }}
